apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: preference
    version: v1
  name: preference-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preference
      version: v1
  template:
    metadata:
      labels:
        app: preference
        version: v1
      annotations:
#        prometheus.io/scrape: "true"
#        prometheus.io/port: "8080"
#        prometheus.io/scheme: "http"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:      
        - name: JAVA_OPTIONS
          value: -Xms8m -Xmx8m -Xmn8m
        image: quay.io/rhdevelopers/istio-tutorial-preference:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        name: preference
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 7
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
